Accompanying Worksheets to Notes in [Introduction to Computational Physics](https://www.amazon.com/Introduction-Computational-Physics-Differential-Simulations/dp/B0GJD4DNNY).

# Worksheet 5: Arrays, Vectorization, Broadcasting and Matrix Operation

- Convert a Python list to a NumPy array and check the shape and dimensions;
- Create a vector $x$ and compute all functional values $f(x)$;
- Broadcasting: compute a 2D grid of potential $V(x,y)$ from 1D vectors $x$ and $y$;
- Basic linear algebra: solve sets of linear equations.

NumPy efficiently stores n-dimensional arrays  and provides matrix operations in linear algebra. It solves eigenvalue problems and provides mathematical functions that are commonly used in physics. The package simplifies element-wise operations on arrays with different shapes using a method called *broadcasting*.

## Example on Broadcasting with Numpy

In [1]:
# use as needed:
# !pip3 install numpy 

In [2]:
import numpy as np 

A = [ [1,1], [2,3] ] # list
# 1.3 * A            # TypeError
1.3 * np.array(A)    # 2x2 matrix

array([[1.3, 1.3],
       [2.6, 3.9]])

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 1: Broadcasting

Use **list comprehension** to create a list with all the squares for $0 < x \le 10$; i.e. [1, 4,..., 100], then convert to a Numpy Array (`ndarray` data type) and multiply each number with 2; the new array will have a sequence of $2x^2$ for integers $x$

In [3]:
# add your list comprehension here
B = ...
# convert to a data type: ndarray
B_ndarray = ...
# multiply each element with a factor of 2 and show the output:
# expect: [2, 8, 18, ..., 200]


Some important attributes of an `np.ndarray` object are the dimensions, the shape of the object, the size and the data types. Here is an example:  

```{python}
A2 = np.array( [[1,2,3], [5,6,7]] )
A2.ndim, A2.shape, A2.size, A2.dtype, A2.nbytes
```

In [4]:
A2 = np.array( [[1,2,3], [5,6,7]] )
A2.ndim, A2.shape, A2.size, A2.dtype, A2.nbytes

(2, (2, 3), 6, dtype('int64'), 48)

## Array Generation

You have many ways of generating an array:  

```{python}
a1 = np.array([4,6,8,2])  # a specific array
a2 = np.zeros(10)         # an array with 10 zeroes
a3 = np.ones(4)           # an array with 4 ones
a4 = np.eye(6)            # 6x6 identity matrix

a5 = np.random.rand(10)   # 10 rnd #s (uniform 0 - 1)
a6 = np.random.randn(10)  # 10 rnd #s (normal dist.) 

a7 = np.linspace(0, 10, 100) # 100 numbers from 0-10
a8 = np.arange(0, 10, 0.2)   # spaced array by 0.2
```

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 2a: Identity Matrix

Create a 10x10 identity matrix, then change element `[0][1]` to 2 and print the matrix; such that the first rows look as follows (use argument `dtype=int` to force an integer instead of a float.)
```
array([[1, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
```

In [5]:
# Modified Identity Matrix
B3 = ...

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 2b: Vector 1

Create a vector with 20 equally-spaced values in the range $-10 \le x \le 10$. Then use `.shape` to check the length of the vector.

In [6]:
# vector with [-10, ..., +10] that has 20 values that are equally spaced.
x_vec = ...


<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 2c: Vector 2

Create another vector $-10 \le x \le 10$ with the spacing of exactly +0.5. Then use `.shape` to check the length of the vector. Verify that the last item is `+10`. You can use `x_vec[-1]` to access the last item.

In [7]:
# vector with [-10, -9.5, -9, ... +9.5, +10] that has spacing +0.5, find the length.
x_vec = ...
x_vec

Ellipsis

## Linear Algebra Operations

The most common algebraic operations that you may encounter in physics are probably solving a system of equations $A \cdot x = b$, invert a matrix $A^{-1} A = 1$ and find eigenvalues by solving $Ax = \lambda x$. These and more operations are implemented in the `NumPy` package.


| function | math | description |
|:-----------------------|:------------------|:----------------------------|
| np.linalg.det(A) | $\|\det A\|$ | determinant of matrix A |
| np.linalg.inv(A) | $A^{-1}$ | inverse of A |
| np.linalg.solve(A, b) | $A x = b$ | solve system of equations |
| np.linalg.eig(A) | $Ax = \lambda x$ | eigenvectors and eigenvalues |
| np.transpose(A) | $A^t$ | transposing of matrix  |
| A \@ B | $A \cdot B$ | matrix multiplication  |
| np.dot(A, x) | $A x$ | dot product  |
| scipy.linalg.lu(A) | $L\cdot (U\cdot x) = b$ | LU decomposition  |

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 3: Linear Algebra

Use numpy to define the matrix 

$$
D = 
\begin{bmatrix}
5 & 2 \\
1 & 3
\end{bmatrix}
$$

Find the transposed matrix $D_1 = D^t$, the inverted matrix $D_2 = D^{-1}$ and the determinant $D_3 = |\text{det} \; D|$.

In [8]:
# transposed matrix


In [9]:
# inverted matrix

In [10]:
# determinant

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 3b: Solve Linear Equation

Solve the following two linear equations by writing them in matrix notation: $Ax = b$. (Use `np.linalg.solve()` to find the solution)

$$
5x - 7y = 11
$$

$$
x + y = 2
$$

Solve for $x$ and $y$. Then verify that you have the correct answers.

In [11]:
# Solve a linear equation


<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 4: Eigenvectors

Find two eigenvectors for the matrix $D$. Use *element access* with `[0]`, etc. to access eigenvalues and eigenvectors. Save the first eigen vector as $v1$ and the second as $v1$, also find the two eigenvalues $e1$ and $e2$. (Use `np.linalg.eig()` to find the eigen vectors and eigen values, use `help()` or look at the results to extract the desired values.)

In [12]:
v1 = ...
v2 = ...
e1 = ...
e2 = ...

In [13]:
print(f"The eigenvalues for matrix D are {e1} and {e2}.")

The eigenvalues for matrix D are Ellipsis and Ellipsis.


## Array Slicing 

*Array slicing* allows you to extract specific portions of a NumPy array. It is like cutting a cake into smaller pieces, you can choose which part of the array you want to work with. Slicing is particularly useful for selecting rows, columns, or subarrays from a larger array.

Accessing a certain portion of an array can be useful. You can create sequences using "start:stop:step". If `start` is left out, it is assumed to be 0. If `stop` is left out, it is assumed to be the last element. For example, A\[1:-2\] goes from the second element to the second from last element. A\[:\] selects everything and A\[::2\] skips every second element.

<div style="background:#e6f2ff; padding:12px 14px; border-radius:8px;">

## Task 5: Slicing

Given the following 10x10 matrix: `Q = np.eye(10, k=1)*3 + np.eye(10) + np.eye(10, k=-1)*2`, extract 4 sub-matrices that contain each quadrant.

</div>

In [14]:
Q = np.eye(10, k=2, dtype=int)*2 + np.eye(10, dtype=int) + np.eye(10, k=-2, dtype=int)*2
Q

array([[1, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 0],
       [2, 0, 1, 0, 2, 0, 0, 0, 0, 0],
       [0, 2, 0, 1, 0, 2, 0, 0, 0, 0],
       [0, 0, 2, 0, 1, 0, 2, 0, 0, 0],
       [0, 0, 0, 2, 0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 2, 0, 1, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 0, 1, 0, 2],
       [0, 0, 0, 0, 0, 0, 2, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 1]])

In [15]:
# Top left Quadrant
Q1 = ...

In [16]:
# Top right Quadrant
Q2 = ...

In [17]:
# Bottom left Quadrant
Q3 = ...

In [18]:
# Top right Quadrant
Q4 = ...