# Homework Chapters 4-5

Numbers correspond to homework problems from [Introduction to Computational Physics](https://www.amazon.com/Introduction-Computational-Physics-Differential-Simulations/dp/B0FL7W88TM)

## Chapter 4

17. Use list comprehension to generate a list with **(a)**  all numbers from 1 to 1000; **(b)**  all even numbers between 100 and 1000 in reverse order; i.e. [1000, 998, 996, ..., 100]; **(c)**  a list with fractional values $1/n$, where $1 < n < 100$. 

In [2]:
# Solution (a)

X = [x for x in range(1,1001)]
X[-1]==1000

True

In [4]:
# Solution (b)

X = [x for x in range(1000,99,-1) if x%2==0]
X[0]==1000, X[-1]==100

(True, True)

In [6]:
# Solution (c)

X = [1/x for x in range(1,101)]
X[0], X[-1]

(1.0, 0.01)

22. **(P)** A projectile is launched from ground level with an initial speed $v_0$ at an angle $\theta$ above the horizontal. From kinematics, the horizontal range $R$ and time of flight $T$ are given by $R =  v_0^2  /g \; \sin(2 \theta_0)$ and $T = 2 v_0 /g \; \sin(\theta_0)$, then  **(a)** Write a function `projectileMotion(v0, th0)` that takes the initial velocity `v0` in m/s and angle `th0` in degrees. It returns a tuple `(R, T)` with the range and time of flight.  **(b)** Using list comprehension, compute the range and flight time for angles between $10^\circ$ and $80^\circ$ (step $5^\circ$), assuming $v_0 = 20 \text{ m/s}$. Output a table with the angles and corresponding range. 

In [10]:
# Solution (a)

from math import radians
import numpy as np

def projectileMotion(v0, th0):
    g = 9.81
    R = v0**2/g*np.sin(2*radians(th0))
    T = 2*v0/g*np.sin(radians(th0))
    return (R,T)

projectileMotion(10,45)

(np.float64(10.19367991845056), np.float64(1.4416040391163045))

In [14]:
# Solution (b)

TH0 = [x for x in range(10,81,5)]
for th0 in TH0:
    v0=20
    R,T = projectileMotion(20, th0)
    print(f"{v0=:3.1f} {th0=:3.1f} has range {R:5.2f} m and flight time {T:3.4f} s")

v0=20.0 th0=10.0 has range 13.95 m and flight time 0.7080 s
v0=20.0 th0=15.0 has range 20.39 m and flight time 1.0553 s
v0=20.0 th0=20.0 has range 26.21 m and flight time 1.3946 s
v0=20.0 th0=25.0 has range 31.24 m and flight time 1.7232 s
v0=20.0 th0=30.0 has range 35.31 m and flight time 2.0387 s
v0=20.0 th0=35.0 has range 38.32 m and flight time 2.3387 s
v0=20.0 th0=40.0 has range 40.16 m and flight time 2.6209 s
v0=20.0 th0=45.0 has range 40.77 m and flight time 2.8832 s
v0=20.0 th0=50.0 has range 40.16 m and flight time 3.1235 s
v0=20.0 th0=55.0 has range 38.32 m and flight time 3.3401 s
v0=20.0 th0=60.0 has range 35.31 m and flight time 3.5312 s
v0=20.0 th0=65.0 has range 31.24 m and flight time 3.6954 s
v0=20.0 th0=70.0 has range 26.21 m and flight time 3.8316 s
v0=20.0 th0=75.0 has range 20.39 m and flight time 3.9385 s
v0=20.0 th0=80.0 has range 13.95 m and flight time 4.0155 s


## Chapter 5


25. Create a 20 x 20 matrix $B = 5 \cdot \mathbb{1}$ with $\mathbb{1}$ as the identity matrix.

In [16]:
# Solution

np.eye(20, dtype=int)*5

array([[5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

29. Create a vector $x$ with  1000 values in the range $-5 \leq x \leq 5$. Compute vector $y=f(x)$ for the function $f(x) = x^2 -2x + 3$ by broadcasting; i.e. do not use a loop. 

In [18]:
# Solution

f = lambda x: x**2 - 2*x + 3
x = np.linspace(-5,5,1000)
y = f(x)

[38.         37.87998008 37.76016056 37.64054144 37.52112272 37.40190441
 37.28288649 37.16406897 37.04545186 36.92703514 36.80881883 36.69080292
 36.5729874  36.45537229 36.33795758 36.22074327 36.10372935 35.98691584
 35.87030274 35.75389003 35.63767772 35.52166581 35.4058543  35.2902432
 35.17483249 35.05962218 34.94461228 34.82980278 34.71519367 34.60078497
 34.48657667 34.37256876 34.25876126 34.14515416 34.03174746 33.91854116
 33.80553526 33.69272977 33.58012467 33.46771997 33.35551568 33.24351178
 33.13170828 33.02010519 32.9087025  32.7975002  32.68649831 32.57569682
 32.46509573 32.35469504 32.24449474 32.13449486 32.02469537 31.91509628
 31.80569759 31.6964993  31.58750142 31.47870393 31.37010684 31.26171016
 31.15351387 31.04551799 30.93772251 30.83012742 30.72273274 30.61553846
 30.50854458 30.4017511  30.29515802 30.18876534 30.08257306 29.97658119
 29.87078971 29.76519863 29.65980796 29.55461768 29.44962781 29.34483833
 29.24024926 29.13586059 29.03167231 28.92768444 28.

33. Find the inverse matrix and verify that $A \cdot A^{-1} = \mathbb{1}$ given $$ A= \begin{pmatrix} 1 & 2 & 0 & 0 & 0 \\ 3 & 5 & 0 & 0 & 0 \\ 0 & 0 & 4 & 0 & 0 \\ 0 & 0 & 0 & 7 & 8 \\ 0 & 0 & 0 & 5 & 6 \\ \end{pmatrix} $$

In [21]:
# Solution
A = [[1,2,0,0,0],[3,5,0,0,0],[0,0,4,0,0],[0,0,0,7,8],[0,0,0,5,6]]
A_inv = np.linalg.inv(A)
A_inv, A @ A_inv

(array([[-5.  ,  2.  ,  0.  ,  0.  ,  0.  ],
        [ 3.  , -1.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.25,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  3.  , -4.  ],
        [ 0.  ,  0.  ,  0.  , -2.5 ,  3.5 ]]),
 array([[1.00000000e+00, 2.22044605e-16, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [4.44089210e-16, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
         0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00]]))

34. **(P)** Diagonalization of a 3x3 Matrix is common in physics. Solving Schrödinger's equation for the bound hydrogen atom, we start with a matrix $A$ that has this shape: $$ A = \begin{bmatrix} 2 & -1 & 0 \\ -1 & 2 & -1 \\ 0 & -1 & 2 \end{bmatrix}$$ This matrix appears in discrete second-derivative approximations.  **(a)**  Use `NumPy` to find its eigenvalues and eigenvectors.  **(b)**  Verify that $A = PDP^{-1}$, where $D$ is the diagonal matrix of eigenvalues and $P$ is the eigenvector matrix.   **(c)**  Discuss the significance of the eigenvalues in terms of vibrational modes.


In [25]:
# Solution (a)

A = [[2,-1,0],[-1,2,-1],[0,-1,2]]
np.linalg.eig(A)

EigResult(eigenvalues=array([3.41421356, 2.        , 0.58578644]), eigenvectors=array([[-5.00000000e-01, -7.07106781e-01,  5.00000000e-01],
       [ 7.07106781e-01,  4.05405432e-16,  7.07106781e-01],
       [-5.00000000e-01,  7.07106781e-01,  5.00000000e-01]]))

In [31]:
# Solution (b)

evec =  np.linalg.eig(A)
D = evec[0]*np.eye(3)
P = np.linalg.eig(A)[1]
P @ D @ np.linalg.inv(P)

array([[ 2.00000000e+00, -1.00000000e+00, -4.99600361e-16],
       [-1.00000000e+00,  2.00000000e+00, -1.00000000e+00],
       [-6.61371711e-16, -1.00000000e+00,  2.00000000e+00]])

# Solution (b)

The eigenvalues correspond to energy levels and the eigenvectors to the wavefunctions.